apiVersion: v1
kind: Service
metadata:
  name: ms-inference-scheduling-decode-direct
  namespace: llmd-is
spec:
  type: ClusterIP
  selector:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: inference-scheduling
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: Qwen3-32B
    llm-d.ai/role: decode
  ports:
  - name: http-vllm
    port: 80
    targetPort: 8000
