apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmd-bench
  namespace: llmd-is
spec:
  storageClassName: standard 
  accessModes:
    #- ReadWriteMany Not needed for a single pod launcher
    - ReadWriteOnce # inference-scheduling templates use parallelism: 1
  resources:
    requests:
      storage: 100Gi
