apiVersion: v1
kind: Service
metadata:
  name: ms-kv-events-direct
spec:
  type: ClusterIP
  selector:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "precise-prefix-cache-aware"
    llm-d.ai/model: "Qwen3-32B"
    llm-d.ai/role: "decode"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: vllm
